#!/bin/bash

print_banner() {
    cat <<'BANNER'
  __  __      _ ____              _
 |  \/  | ___| | ___   _ _ __ ___| |__   ___ _ __ ___
 | |\/| |/ _ \ | | | | | | '__/ __| '_ \ / _ \ '__/ __|
 | |  | |  __/ | | |_| | | | | (__| | | |  __/ |  \__ \
 |_|  |_|\___|_|_|\__,_|_|_|  \___|_| |_|\___|_|  |___/

              Universal Metadata Sanitizer - Installer
                  (auto-installs all dependencies)
BANNER
}

print_banner

if [ -n "$TERMUX_VERSION" ] || [ -d "/data/data/com.termux/files/usr" ]; then
    INSTALL_KIND="termux"
    PREFIX_DIR="${PREFIX:-/data/data/com.termux/files/usr}"
    BIN_DIR="$PREFIX_DIR/bin"
    SHARE_DIR="$PREFIX_DIR/share/metaclean"
    PYTHON_BIN="python3"
elif [[ "$(uname -s)" == "Darwin" ]]; then
    INSTALL_KIND="macos"
    BIN_DIR="$HOME/.local/bin"
    SHARE_DIR="$HOME/.local/share/metaclean"
    PYTHON_BIN="python3"
elif [[ "$(uname -s)" == "MINGW"* || "$(uname -s)" == "MSYS"* || "$(uname -s)" == "CYGWIN"* ]]; then
    INSTALL_KIND="msys"
    BIN_DIR="$HOME/.local/bin"
    SHARE_DIR="$HOME/.local/share/metaclean"
    PYTHON_BIN="python3"
else
    INSTALL_KIND="linux"
    BIN_DIR="$HOME/.local/bin"
    SHARE_DIR="$HOME/.local/share/metaclean"
    PYTHON_BIN="python3"
fi

if ! command -v "$PYTHON_BIN" >/dev/null 2>&1; then
    PYTHON_BIN="python"
fi

if ! command -v "$PYTHON_BIN" >/dev/null 2>&1; then
    echo "ERROR: Python 3 is required but was not found on PATH."
    echo "Install Python 3 first:"
    case "$INSTALL_KIND" in
        termux) echo "  pkg install python" ;;
        macos)  echo "  brew install python" ;;
        linux)  echo "  sudo apt install python3   (or your distro's equivalent)" ;;
    esac
    exit 1
fi

PY_VERSION="$($PYTHON_BIN -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')"
if [ "${PY_VERSION%%.*}" -lt 3 ] || { [ "${PY_VERSION%%.*}" -eq 3 ] && [ "${PY_VERSION#*.}" -lt 10 ]; }; then
    echo "ERROR: Python 3.10+ is required. Detected: $PY_VERSION"
    exit 1
fi
echo "[+] Python detected: $PY_VERSION ($($PYTHON_BIN -c 'import sys; print(sys.executable)'))"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [ ! -f "$SCRIPT_DIR/metaclean.py" ]; then
    echo "ERROR: metaclean.py not found in $SCRIPT_DIR"
    echo "Run this installer from the directory containing metaclean.py"
    exit 1
fi

echo "[+] Platform: $INSTALL_KIND"
echo "[+] Install bin:   $BIN_DIR"
echo "[+] Install share: $SHARE_DIR"
echo

mkdir -p "$BIN_DIR" "$SHARE_DIR"

echo "[+] Copying metaclean.py to $SHARE_DIR/metaclean.py"
cp "$SCRIPT_DIR/metaclean.py" "$SHARE_DIR/metaclean.py"
chmod 644 "$SHARE_DIR/metaclean.py"

WRAPPER="$BIN_DIR/metaclean"
echo "[+] Creating wrapper script at $WRAPPER"
cat > "$WRAPPER" <<EOF
#!/bin/sh
# Auto-generated by MetaClean installer.
# Do not edit manually; re-run install.sh to update.
exec "$PYTHON_BIN" "$SHARE_DIR/metaclean.py" "\$@"
EOF
chmod +x "$WRAPPER"

echo
echo "=============================================="
echo "  Checking external dependencies..."
echo "=============================================="
echo

MISSING_TOOLS=()
check_tool() {
    local tool="$1"
    if command -v "$tool" >/dev/null 2>&1; then
        echo "[+] $tool: found ($(command -v "$tool"))"
        return 0
    else
        echo "[!] $tool: NOT found"
        MISSING_TOOLS+=("$tool")
        return 1
    fi
}

check_tool exiftool
check_tool ffmpeg
check_tool qpdf

if [ ${#MISSING_TOOLS[@]} -eq 0 ]; then
    echo
    echo "[+] All external dependencies are already installed."
else
    echo
    echo "Missing tools: ${MISSING_TOOLS[*]}"
    echo
    echo "=============================================="
    echo "  Auto-installing missing dependencies..."
    echo "=============================================="
    echo

    install_via_pkg() {
        local tool="$1"
        case "$tool" in
            exiftool)
                echo "[*] Installing exiftool via pkg (Termux)..."
                pkg install -y perl || true
                cpan -f -i Image::ExifTool 2>&1 | tail -3 || true
                ;;
            ffmpeg)
                echo "[*] Installing ffmpeg via pkg (Termux)..."
                pkg install -y ffmpeg || true
                ;;
            qpdf)
                echo "[*] Installing qpdf via pkg (Termux)..."
                pkg install -y qpdf || true
                ;;
        esac
    }

    install_via_apt() {
        local tool="$1"
        local pm="$2"
        local pkg_name=""
        case "$tool" in
            exiftool) pkg_name="libimage-exiftool-perl" ;;
            ffmpeg)   pkg_name="ffmpeg" ;;
            qpdf)     pkg_name="qpdf" ;;
        esac
        echo "[*] Installing $tool via $pm (package: $pkg_name)..."
        (sudo -n $pm install -y "$pkg_name" 2>/dev/null || sudo $pm install -y "$pkg_name" || $pm install -y "$pkg_name") || true
    }

    install_via_dnf() {
        local tool="$1"
        local pm="$2"
        local pkg_name=""
        case "$tool" in
            exiftool) pkg_name="perl-Image-ExifTool" ;;
            ffmpeg)   pkg_name="ffmpeg" ;;
            qpdf)     pkg_name="qpdf" ;;
        esac
        echo "[*] Installing $tool via $pm (package: $pkg_name)..."
        (sudo -n $pm install -y "$pkg_name" 2>/dev/null || sudo $pm install -y "$pkg_name" || $pm install -y "$pkg_name") || true
    }

    install_via_pacman() {
        local tool="$1"
        local pkg_name=""
        case "$tool" in
            exiftool) pkg_name="perl-image-exiftool" ;;
            ffmpeg)   pkg_name="ffmpeg" ;;
            qpdf)     pkg_name="qpdf" ;;
        esac
        echo "[*] Installing $tool via pacman (package: $pkg_name)..."
        (sudo -n pacman -S --noconfirm "$pkg_name" 2>/dev/null || sudo pacman -S --noconfirm "$pkg_name" || pacman -S --noconfirm "$pkg_name") || true
    }

    install_via_zypper() {
        local tool="$1"
        local pkg_name=""
        case "$tool" in
            exiftool) pkg_name="perl-Image-ExifTool" ;;
            ffmpeg)   pkg_name="ffmpeg" ;;
            qpdf)     pkg_name="qpdf" ;;
        esac
        echo "[*] Installing $tool via zypper (package: $pkg_name)..."
        (sudo -n zypper --non-interactive install "$pkg_name" 2>/dev/null || sudo zypper --non-interactive install "$pkg_name" || zypper --non-interactive install "$pkg_name") || true
    }

    install_via_apk() {
        local tool="$1"
        local pkg_name=""
        case "$tool" in
            exiftool) pkg_name="exiftool" ;;
            ffmpeg)   pkg_name="ffmpeg" ;;
            qpdf)     pkg_name="qpdf" ;;
        esac
        echo "[*] Installing $tool via apk (package: $pkg_name)..."
        (doas apk add --no-cache "$pkg_name" 2>/dev/null || sudo -n apk add --no-cache "$pkg_name" 2>/dev/null || apk add --no-cache "$pkg_name") || true
    }

    install_via_brew() {
        local tool="$1"
        echo "[*] Installing $tool via brew..."
        brew install "$tool" || true
    }

    for tool in "${MISSING_TOOLS[@]}"; do
        case "$INSTALL_KIND" in
            termux)
                install_via_pkg "$tool"
                ;;
            macos)
                if command -v brew >/dev/null 2>&1; then
                    install_via_brew "$tool"
                else
                    echo "[!] Homebrew not found. Installing Homebrew first..."
                    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
                    install_via_brew "$tool"
                fi
                ;;
            linux)
                if command -v apt >/dev/null 2>&1; then
                    install_via_apt "$tool" "apt"
                elif command -v apt-get >/dev/null 2>&1; then
                    install_via_apt "$tool" "apt-get"
                elif command -v dnf >/dev/null 2>&1; then
                    install_via_dnf "$tool" "dnf"
                elif command -v yum >/dev/null 2>&1; then
                    install_via_dnf "$tool" "yum"
                elif command -v pacman >/dev/null 2>&1; then
                    install_via_pacman "$tool"
                elif command -v zypper >/dev/null 2>&1; then
                    install_via_zypper "$tool"
                elif command -v apk >/dev/null 2>&1; then
                    install_via_apk "$tool"
                else
                    echo "[!] No supported package manager found for $tool"
                    echo "    Please install $tool manually."
                fi
                ;;
            msys)
                echo "[!] On MSYS2/Windows, please install $tool manually:"
                echo "    - exiftool: download from https://exiftool.org/"
                echo "    - ffmpeg:   pacman -S mingw-w64-x86_64-ffmpeg"
                echo "    - qpdf:     pacman -S mingw-w64-x86_64-qpdf"
                ;;
        esac
        echo
    done

    echo "=============================================="
    echo "  Verifying installations..."
    echo "=============================================="
    STILL_MISSING=()
    for tool in "${MISSING_TOOLS[@]}"; do
        if command -v "$tool" >/dev/null 2>&1; then
            echo "[+] $tool: installed successfully"
        else
            echo "[!] $tool: still missing (may need a new terminal or manual install)"
            STILL_MISSING+=("$tool")
        fi
    done

    if [ ${#STILL_MISSING[@]} -gt 0 ]; then
        echo
        echo "Note: Some tools could not be auto-installed."
        echo "MetaClean will still work for formats that don't need them."
        echo "Missing: ${STILL_MISSING[*]}"
    fi
fi

add_to_path_in_file() {
    local rc_file="$1"
    local path_line="export PATH=\"$BIN_DIR:\$PATH\""
    if [ ! -f "$rc_file" ]; then
        touch "$rc_file"
    fi
    if ! grep -qF "$BIN_DIR" "$rc_file"; then
        {
            echo ""
            echo "# Added by MetaClean installer"
            echo "$path_line"
        } >> "$rc_file"
        echo "[+] Added $BIN_DIR to PATH in $rc_file"
        return 0
    fi
    return 1
}

PATH_UPDATED=0
case "$INSTALL_KIND" in
    termux)
        add_to_path_in_file "$HOME/.bashrc" && PATH_UPDATED=1
        ;;
    macos)
        if [ -n "$ZSH_VERSION" ] || [ ! -f "$HOME/.bash_profile" ]; then
            add_to_path_in_file "$HOME/.zshrc" && PATH_UPDATED=1
        fi
        if [ -f "$HOME/.bash_profile" ]; then
            add_to_path_in_file "$HOME/.bash_profile" && PATH_UPDATED=1
        fi
        ;;
    linux|msys)
        if [ -n "$ZSH_VERSION" ] || [ -f "$HOME/.zshrc" ]; then
            add_to_path_in_file "$HOME/.zshrc" && PATH_UPDATED=1
        fi
        if [ -n "$BASH_VERSION" ] || [ -f "$HOME/.bashrc" ] || [ ! -f "$HOME/.profile" ]; then
            add_to_path_in_file "$HOME/.bashrc" && PATH_UPDATED=1
        fi
        add_to_path_in_file "$HOME/.profile" && PATH_UPDATED=1
        ;;
esac

if [ -d "$HOME/.config/fish" ]; then
    FISH_RC="$HOME/.config/fish/config.fish"
    if [ ! -f "$FISH_RC" ] || ! grep -qF "$BIN_DIR" "$FISH_RC"; then
        mkdir -p "$HOME/.config/fish"
        {
            echo ""
            echo "# Added by MetaClean installer"
            echo "set -gx PATH $BIN_DIR \$PATH"
        } >> "$FISH_RC"
        echo "[+] Added $BIN_DIR to PATH in $FISH_RC"
        PATH_UPDATED=1
    fi
fi

echo
echo "=============================================="
echo "  MetaClean installation complete!"
echo "=============================================="
echo
echo "Installed to: $SHARE_DIR/metaclean.py"
echo "Command:      $WRAPPER"
echo

if command -v metaclean >/dev/null 2>&1; then
    echo "[+] Verification: metaclean is on PATH"
    metaclean --version
    echo
    echo "You can now run 'metaclean' from any directory."
else
    if [ "$PATH_UPDATED" -eq 1 ]; then
        echo "To start using metaclean immediately, either:"
        echo "  1. Open a new terminal, OR"
        echo "  2. Run: source ~/.bashrc  (or ~/.zshrc)"
        echo
        echo "Or activate for the current shell:"
        echo "  export PATH=\"$BIN_DIR:\$PATH\""
    else
        echo "To activate metaclean, add $BIN_DIR to your PATH:"
        echo "  export PATH=\"$BIN_DIR:\$PATH\""
        echo
        echo "Or run metaclean directly:"
        echo "  $WRAPPER --help"
    fi
fi

echo
echo "Quick start:"
echo "  metaclean                          # interactive mode"
echo "  metaclean photo.jpg                # inspect + offer to clean"
echo "  metaclean --scan photo.jpg         # scan only"
echo "  metaclean --clean --yes photo.jpg  # non-interactive clean"
echo "  metaclean --help                   # full options"
echo
echo "To uninstall later: rm $WRAPPER $SHARE_DIR/metaclean.py"
